a = input('digite algo: ')
print('só tem espaços?',a.isspace())
print('é um numero?',a.isnumeric())
print('é alfabeto?',a.isalpha())
print('é alfanumerico?',a.isalnum())
print('está em maiusculas?',a.isupper())
print('está em minusculas?',a.islower())
print('está capitalizada?',a.istitle())